controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Rev9
      - Rev8
      - Rev11
      - Rev3
      - Rev10
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - Rev6
      - Rev7
initial:  # Define initial robot poses per group
  - group: arm
    pose: start
  - group: gripper
    pose: home