spot_w_arm:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position controllers and set up PID for Spot

  LF_HAA_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_HAA
    pid: {p: 700, i: 50, d: 70}

  LH_HAA_position_controller:
    type: effort_controllers/JointPositionController
    joint: LH_HAA
    pid: { p: 700, i: 50, d: 70 }

  RF_HAA_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_HAA
    pid: { p: 700, i: 50, d: 70 }

  RH_HAA_position_controller:
    type: effort_controllers/JointPositionController
    joint: RH_HAA
    pid: { p: 700, i: 50, d: 70 }

  LF_HFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_HFE
    pid: { p: 700, i: 50, d: 70 }

  LH_HFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: LH_HFE
    pid: { p: 700, i: 50, d: 70 }

  RF_HFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_HFE
    pid: { p: 700, i: 50, d: 70 }

  RH_HFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: RH_HFE
    pid: { p: 700, i: 50, d: 70 }

  LF_KFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_KFE
    pid: { p: 700, i: 50, d: 70 }

  LH_KFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: LH_KFE
    pid: { p: 700, i: 50, d: 70 }

  RF_KFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_KFE
    pid: { p: 700, i: 50, d: 70 }

  RH_KFE_position_controller:
    type: effort_controllers/JointPositionController
    joint: RH_KFE
    pid: { p: 700, i: 50, d: 70 }



  # Position controllers and set up PID for arm
  #base->part1
  Rev9_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev9
    pid: { p: 30000.0, i: 5.0, d: 10.0 }
  #part1->part2
  Rev8_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev8
    pid: { p: 2000.0, i: 5.0, d: 10.0 }

  Rev11_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev11
    pid: { p: 2000.0, i: 5.0, d: 10.0 }

  Rev3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev3
    pid: { p: 2000.0, i: 5.0, d: 10.0 }

  Rev10_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev10
    pid: { p: 2000.0, i: 5.0, d: 10.0 }

  Rev6_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev6
    pid: { p: 2000.0, i: 5.0, d: 10.0 }

  Rev7_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev7
    pid: { p: 2000.0, i: 5.0, d: 10.0 }


